sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/nim-base
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/nim-base nim --version
  - docker run -v "$(pwd):/project" -w /project yglukhov/nim-base sh -c "apt-get update && nimble update && nimble install -dy"
